### ISSUE TITLE
Things to consider

### ISSUE THREAD

**Issue by RahulNavneeth** [bitspaceorg/bitspace#7]
**red:** inconsistent font
**green:** would work without that img
**blue:** increase spacing between the nav contents
**yellow:** sexy footer there

<img width="2020" alt="Screenshot 2024-06-08 at 1 25 28 PM" src="https://github.com/bitspaceorg/bitspace/assets/50259284/5ca0cc67-290f-4c72-9771-ec65db036a59">

**Comment by MKMukeshkannan** [comment]
Sorry Bro, We regret to inform you that the website is completely revamped. 😞

**Comment by RahulNavneeth** [comment]
womp womp
